steps:
 # Build the container image
- name: 'node'
  entrypoint: 'npm'
  args: ['install']
- name: 'node'
  entrypoint: 'npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/chek-back-v1', '.']
images: ['gcr.io/$PROJECT_ID/chek-back-v1']